using GeoStats
import Meshes: Point
import CoordRefSystems: LatLon
import Match: @match
import DataFrames: DataFrame
import GeoTables: GeoTable
import JSON: parsefile
import Base.Threads: @spawn

function build_place_table(dir::String)::GeoTable
    raw_places::Vector{Dict{String,Any}} = []
    @sync begin
        for place in readdir(dir)
            @async push!(raw_places, parsefile(dir * place))
        end
    end

    place_id::Vector{String} = []
    primary_type::Vector{Union{String,Missing}} = []
    geometry::Vector{Point} = []

    for place in raw_places
        push!(place_id, get(raw_places[575], "id", ""))
        push!(
            geometry, Point(LatLon{WGS84Latest}(place["location"]["latitude"], place["location"]["longitude"]))
        )
        push!(primary_type, get(place, "primaryType", missing))
    end

    table = DataFrame(; place_id=place_id, primary_type=primary_type)


    return georef(table, geometry)
end

map_top_place_category(category::String) = @match category begin
    "car_dealer" => "AUTOMOTIVE"
    "car_rental" => "AUTOMOTIVE"
    "car_repair" => "AUTOMOTIVE"
    "car_wash" => "AUTOMOTIVE"
    "electric_vehicle_charging_station" => "AUTOMOTIVE"
    "gas_station" => "AUTOMOTIVE"
    "parking" => "AUTOMOTIVE"
    "rest_stop" => "AUTOMOTIVE"
    "farm" => "BUSINESS"
    "art_gallery" => "CULTURE"
    "museum" => "CULTURE"
    "performing_arts_theater" => "CULTURE"
    "library" => "EDUCATION"
    "preschool" => "EDUCATION"
    "primary_schoolschool" => "EDUCATION"
    "secondary_school" => "EDUCATION"
    "university" => "EDUCATION"
    "school" => "EDUCATION"
    "amusement_center" => "RECREATION"
    "amusement_park" => "RECREATION"
    "aquarium" => "RECREATION"
    "banquet_hall" => "RECREATION"
    "bowling_alley" => "RECREATION"
    "casino" => "RECREATION"
    "community_center" => "RECREATION"
    "convention_center" => "RECREATION"
    "cultural_center" => "RECREATION"
    "dog_park" => "RECREATION"
    "event_venue" => "RECREATION"
    "hiking_area" => "RECREATION"
    "historical_landmark" => "RECREATION"
    "marina" => "RECREATION"
    "movie_rental" => "RECREATION"
    "movie_theater" => "RECREATION"
    "national_park" => "RECREATION"
    "night_club" => "RECREATION"
    "park" => "RECREATION"
    "tourist_attraction" => "RECREATION"
    "visitor_center" => "RECREATION"
    "wedding_venue" => "RECREATION"
    "zoo" => "RECREATION"
    "accounting" => "FINANCE"
    "atm" => "FINANCE"
    "bank" => "FINANCE"
    "american_restaurant" => "FOODBEV"
    "bakery" => "FOODBEV"
    "bar" => "FOODBEV"
    "barbecue_restaurant" => "FOODBEV"
    "brazilian_restaurant" => "FOODBEV"
    "breakfast_restaurant" => "FOODBEV"
    "brunch_restaurant" => "FOODBEV"
    "cafe" => "FOODBEV"
    "chinese_restaurant" => "FOODBEV"
    "coffee_shop" => "FOODBEV"
    "fast_food_restaurant" => "FOODBEV"
    "french_restaurant" => "FOODBEV"
    "greek_restaurant" => "FOODBEV"
    "hamburger_restaurant" => "FOODBEV"
    "ice_cream_shop" => "FOODBEV"
    "indian_restaurant" => "FOODBEV"
    "indonesian_restaurant" => "FOODBEV"
    "italian_restaurant" => "FOODBEV"
    "japanese_restaurant" => "FOODBEV"
    "korean_restaurant" => "FOODBEV"
    "lebanese_restaurant" => "FOODBEV"
    "meal_delivery" => "FOODBEV"
    "meal_takeaway" => "FOODBEV"
    "mediterranean_restaurant" => "FOODBEV"
    "mexican_restaurant" => "FOODBEV"
    "middle_eastern_restaurant" => "FOODBEV"
    "pizza_restaurant" => "FOODBEV"
    "ramen_restaurant" => "FOODBEV"
    "restaurant" => "FOODBEV"
    "sandwich_shop" => "FOODBEV"
    "seafood_restaurant" => "FOODBEV"
    "spanish_restaurant" => "FOODBEV"
    "steak_house" => "FOODBEV"
    "sushi_restaurant" => "FOODBEV"
    "thai_restaurant" => "FOODBEV"
    "turkish_restaurant" => "FOODBEV"
    "vegan_restaurant" => "FOODBEV"
    "vegetarian_restaurant" => "FOODBEV"
    "vietnamese_restaurant" => "FOODBEV"
    # "administrative_area_level_1" => "GEOGRAPHIC"
    # "administrative_area_level_2" => "GEOGRAPHIC"
    # "country" => "GEOGRAPHIC"
    # "locality" => "GEOGRAPHIC"
    # "postal_code" => "GEOGRAPHIC"
    # "school_district" => "GEOGRAPHIC"
    "city_hall" => "GOVERNMENT"
    "courthouse" => "GOVERNMENT"
    "embassy" => "GOVERNMENT"
    "fire_station" => "GOVERNMENT"
    "local_GOVERNMENT_office" => "GOVERNMENT"
    "police" => "GOVERNMENT"
    "post_office" => "GOVERNMENT"
    "dental_clinic" => "HEALTH"
    "dentist" => "HEALTH"
    "doctor" => "HEALTH"
    "drugstore" => "HEALTH"
    "hospital" => "HEALTH"
    "medical_lab" => "HEALTH"
    "pharmacy" => "HEALTH"
    "physiotherapist" => "HEALTH"
    "spa" => "HEALTH"
    "bed_and_breakfast" => "LODGING"
    "campground" => "LODGING"
    "camping_cabin" => "LODGING"
    "cottage" => "LODGING"
    "extended_stay_hotel" => "LODGING"
    "farmstay" => "LODGING"
    "guest_house" => "LODGING"
    "hostel" => "LODGING"
    "hotel" => "LODGING"
    "LODGING" => "LODGING"
    "motel" => "LODGING"
    "private_guest_room" => "LODGING"
    "resort_hotel" => "LODGING"
    "rv_park" => "LODGING"
    "church" => "WORSHIP"
    "hindu_temple" => "WORSHIP"
    "mosque" => "WORSHIP"
    "synagogue" => "WORSHIP"
    "barber_shop" => "SERVICES"
    "beauty_salon" => "SERVICES"
    "cemetery" => "SERVICES"
    "child_care_agency" => "SERVICES"
    "consultant" => "SERVICES"
    "courier_service" => "SERVICES"
    "electrician" => "SERVICES"
    "florist" => "SERVICES"
    "funeral_home" => "SERVICES"
    "hair_care" => "SERVICES"
    "hair_salon" => "SERVICES"
    "insurance_agency" => "SERVICES"
    "laundry" => "SERVICES"
    "lawyer" => "SERVICES"
    "locksmith" => "SERVICES"
    "moving_company" => "SERVICES"
    "painter" => "SERVICES"
    "plumber" => "SERVICES"
    "real_estate_agency" => "SERVICES"
    "roofing_contractor" => "SERVICES"
    "storage" => "SERVICES"
    "tailor" => "SERVICES"
    "telecommunications_service_provider" => "SERVICES"
    "travel_agency" => "SERVICES"
    "veterinary_care" => "SERVICES"
    "auto_parts_store" => "SHOPPING"
    "bicycle_store" => "SHOPPING"
    "book_store" => "SHOPPING"
    "cell_phone_store" => "SHOPPING"
    "clothing_store" => "SHOPPING"
    "convenience_store" => "SHOPPING"
    "department_store" => "SHOPPING"
    "discount_store" => "SHOPPING"
    "electronics_store" => "SHOPPING"
    "furniture_store" => "SHOPPING"
    "gift_shop" => "SHOPPING"
    "grocery_store" => "SHOPPING"
    "hardware_store" => "SHOPPING"
    "home_goods_store" => "SHOPPING"
    "home_improvement_store" => "SHOPPING"
    "jewelry_store" => "SHOPPING"
    "liquor_store" => "SHOPPING"
    "market" => "SHOPPING"
    "pet_store" => "SHOPPING"
    "shoe_store" => "SHOPPING"
    "SHOPPING_mall" => "SHOPPING"
    "sporting_goods_store" => "SHOPPING"
    "store" => "SHOPPING"
    "supermarket" => "SHOPPING"
    "wholesaler" => "SHOPPING"
    "athletic_field" => "SHOPPING"
    "fitness_center" => "SHOPPING"
    "golf_course" => "SHOPPING"
    "gym" => "SHOPPING"
    "playground" => "SHOPPING"
    "ski_resort" => "SHOPPING"
    "sports_club" => "SHOPPING"
    "sports_complex" => "SHOPPING"
    "stadium" => "SHOPPING"
    "swimming_pool" => "SHOPPING"
    "airport" => "TRANSPORTATION"
    "bus_station" => "TRANSPORTATION"
    "bus_stop" => "TRANSPORTATION"
    "ferry_terminal" => "TRANSPORTATION"
    "heliport" => "TRANSPORTATION"
    "light_rail_station" => "TRANSPORTATION"
    "park_and_ride" => "TRANSPORTATION"
    "subway_station" => "TRANSPORTATION"
    "taxi_stand" => "TRANSPORTATION"
    "train_station" => "TRANSPORTATION"
    "transit_depot" => "TRANSPORTATION"
    "transit_station" => "TRANSPORTATION"
    "truck_stop" => "TRANSPORTATION"
    # "administrative_area_level_3" => "typeb"
    # "administrative_area_level_4" => "typeb"
    # "administrative_area_level_5" => "typeb"
    # "administrative_area_level_6" => "typeb"
    # "administrative_area_level_7" => "typeb"
    # "archipelago" => "typeb"
    # "colloquial_area" => "typeb"
    # "continent" => "typeb"
    # "establishment" => "typeb"
    # "floor" => "typeb"
    # "food" => "typeb"
    # "general_contractor" => "typeb"
    # "geocode" => "typeb"
    # "HEALTH" => "typeb"
    # "intersection" => "typeb"
    # "landmark" => "typeb"
    # "natural_feature" => "typeb"
    # "neighborhood" => "typeb"
    # "place_of_WORSHIP" => "typeb"
    # "plus_code" => "typeb"
    # "point_of_interest" => "typeb"
    # "political" => "typeb"
    # "post_box" => "typeb"
    # "postal_code_prefix" => "typeb"
    # "postal_code_suffix" => "typeb"
    # "postal_town" => "typeb"
    # "premise" => "typeb"
    # "room" => "typeb"
    # "route" => "typeb"
    # "street_address" => "typeb"
    # "street_number" => "typeb"
    # "sublocality" => "typeb"
    # "sublocality_level_1" => "typeb"
    # "sublocality_level_2" => "typeb"
    # "sublocality_level_3" => "typeb"
    # "sublocality_level_4" => "typeb"
    # "sublocality_level_5" => "typeb"
    # "subpremise" => "typeb"
    # "town_square" => "typeb"
    _ => ""
end
