using GeoStats
import Meshes: Point
import CoordRefSystems: LatLon
import Match: @match
import DataFrames: DataFrame
import GeoTables: GeoTable
import JSON: parsefile
import Base.Threads: @spawn

function build_place_table(dir::String)::GeoTable
    raw_places::Vector{Dict{String,Any}} = []
    @sync begin
        for place in readdir(dir)
            @async push!(raw_places, parsefile(dir * place))
        end
    end

    place_id::Vector{String} = []
    primary_type::Vector{Union{String,Missing}} = []
    geometry::Vector{Point} = []

    for place in raw_places
        push!(place_id, Base.get(place, "id", ""))
        push!(
            geometry,
            Point(
                LatLon{WGS84Latest}(
                    place["location"]["latitude"],
                    place["location"]["longitude"],
                ),
            ),
        )
        push!(primary_type, Base.get(place, "primaryType", missing))
    end

    return georef((place_id=place_id, primary_type=primary_type), geometry)
end

map_top_place_category(category::String) = @match category begin
    # Automotive
    "car_dealer" => "AUTOMOTIVE"
    "car_rental" => "AUTOMOTIVE"
    "car_repair" => "AUTOMOTIVE"
    "car_wash" => "AUTOMOTIVE"
    "electric_vehicle_charging_station" => "AUTOMOTIVE"
    "gas_station" => "AUTOMOTIVE"
    "parking" => "AUTOMOTIVE"
    "rest_stop" => "AUTOMOTIVE"
    # Business
    "corporate_office" => "BUSINESS"
    "farm" => "BUSINESS"
    "ranch" => "BUSINESS"
    # Culture
    "art_gallery" => "CULTURE"
    "art_studio" => "CULTURE"
    "auditorium" => "CULTURE"
    "cultural_landmark" => "CULTURE"
    "historical_place" => "CULTURE"
    "monument" => "CULTURE"
    "museum" => "CULTURE"
    "performing_arts_theater" => "CULTURE"
    "sculpture" => "CULTURE"
    # Education
    "library" => "EDUCATION"
    "preschool" => "EDUCATION"
    "primary_school" => "EDUCATION"
    "school" => "EDUCATION"
    "secondary_school" => "EDUCATION"
    "university" => "EDUCATION"
    # Entertainment and Recreation
    "adventure_sports_center" => "ENTERTAINMENT_RECREATION"
    "amphitheatre" => "ENTERTAINMENT_RECREATION"
    "amusement_center" => "ENTERTAINMENT_RECREATION"
    "amusement_park" => "ENTERTAINMENT_RECREATION"
    "aquarium" => "ENTERTAINMENT_RECREATION"
    "banquet_hall" => "ENTERTAINMENT_RECREATION"
    "barbecue_area" => "ENTERTAINMENT_RECREATION"
    "botanical_garden" => "ENTERTAINMENT_RECREATION"
    "bowling_alley" => "ENTERTAINMENT_RECREATION"
    "casino" => "ENTERTAINMENT_RECREATION"
    "childrens_camp" => "ENTERTAINMENT_RECREATION"
    "comedy_club" => "ENTERTAINMENT_RECREATION"
    "community_center" => "ENTERTAINMENT_RECREATION"
    "concert_hall" => "ENTERTAINMENT_RECREATION"
    "convention_center" => "ENTERTAINMENT_RECREATION"
    "cultural_center" => "ENTERTAINMENT_RECREATION"
    "cycling_park" => "ENTERTAINMENT_RECREATION"
    "dance_hall" => "ENTERTAINMENT_RECREATION"
    "dog_park" => "ENTERTAINMENT_RECREATION"
    "event_venue" => "ENTERTAINMENT_RECREATION"
    "ferris_wheel" => "ENTERTAINMENT_RECREATION"
    "garden" => "ENTERTAINMENT_RECREATION"
    "hiking_area" => "ENTERTAINMENT_RECREATION"
    "historical_landmark" => "ENTERTAINMENT_RECREATION"
    "internet_cafe" => "ENTERTAINMENT_RECREATION"
    "karaoke" => "ENTERTAINMENT_RECREATION"
    "marina" => "ENTERTAINMENT_RECREATION"
    "movie_rental" => "ENTERTAINMENT_RECREATION"
    "movie_theater" => "ENTERTAINMENT_RECREATION"
    "national_park" => "ENTERTAINMENT_RECREATION"
    "night_club" => "ENTERTAINMENT_RECREATION"
    "observation_deck" => "ENTERTAINMENT_RECREATION"
    "off_roading_area" => "ENTERTAINMENT_RECREATION"
    "opera_house" => "ENTERTAINMENT_RECREATION"
    "park" => "ENTERTAINMENT_RECREATION"
    "philharmonic_hall" => "ENTERTAINMENT_RECREATION"
    "picnic_ground" => "ENTERTAINMENT_RECREATION"
    "planetarium" => "ENTERTAINMENT_RECREATION"
    "plaza" => "ENTERTAINMENT_RECREATION"
    "roller_coaster" => "ENTERTAINMENT_RECREATION"
    "skateboard_park" => "ENTERTAINMENT_RECREATION"
    "state_park" => "ENTERTAINMENT_RECREATION"
    "tourist_attraction" => "ENTERTAINMENT_RECREATION"
    "video_arcade" => "ENTERTAINMENT_RECREATION"
    "visitor_center" => "ENTERTAINMENT_RECREATION"
    "water_park" => "ENTERTAINMENT_RECREATION"
    "wedding_venue" => "ENTERTAINMENT_RECREATION"
    "wildlife_park" => "ENTERTAINMENT_RECREATION"
    "wildlife_refuge" => "ENTERTAINMENT_RECREATION"
    "zoo" => "ENTERTAINMENT_RECREATION"
    # Facilities
    "public_bath" => "FACILITIES"
    "public_bathroom" => "FACILITIES"
    "stable" => "FACILITIES"
    # Finance
    "accounting" => "FINANCE"
    "atm" => "FINANCE"
    "bank" => "FINANCE"
    # Food and Drink
    "acai_shop" => "FOOD_DRINK"
    "afghani_restaurant" => "FOOD_DRINK"
    "african_restaurant" => "FOOD_DRINK"
    "american_restaurant" => "FOOD_DRINK"
    "asian_restaurant" => "FOOD_DRINK"
    "bagel_shop" => "FOOD_DRINK"
    "bakery" => "FOOD_DRINK"
    "bar" => "FOOD_DRINK"
    "bar_and_grill" => "FOOD_DRINK"
    "barbecue_restaurant" => "FOOD_DRINK"
    "brazilian_restaurant" => "FOOD_DRINK"
    "breakfast_restaurant" => "FOOD_DRINK"
    "brunch_restaurant" => "FOOD_DRINK"
    "buffet_restaurant" => "FOOD_DRINK"
    "cafe" => "FOOD_DRINK"
    "cafeteria" => "FOOD_DRINK"
    "candy_store" => "FOOD_DRINK"
    "cat_cafe" => "FOOD_DRINK"
    "chinese_restaurant" => "FOOD_DRINK"
    "chocolate_factory" => "FOOD_DRINK"
    "chocolate_shop" => "FOOD_DRINK"
    "coffee_shop" => "FOOD_DRINK"
    "confectionery" => "FOOD_DRINK"
    "deli" => "FOOD_DRINK"
    "dessert_restaurant" => "FOOD_DRINK"
    "dessert_shop" => "FOOD_DRINK"
    "diner" => "FOOD_DRINK"
    "dog_cafe" => "FOOD_DRINK"
    "donut_shop" => "FOOD_DRINK"
    "fast_food_restaurant" => "FOOD_DRINK"
    "fine_dining_restaurant" => "FOOD_DRINK"
    "food_court" => "FOOD_DRINK"
    "french_restaurant" => "FOOD_DRINK"
    "greek_restaurant" => "FOOD_DRINK"
    "hamburger_restaurant" => "FOOD_DRINK"
    "ice_cream_shop" => "FOOD_DRINK"
    "indian_restaurant" => "FOOD_DRINK"
    "indonesian_restaurant" => "FOOD_DRINK"
    "italian_restaurant" => "FOOD_DRINK"
    "japanese_restaurant" => "FOOD_DRINK"
    "juice_shop" => "FOOD_DRINK"
    "korean_restaurant" => "FOOD_DRINK"
    "lebanese_restaurant" => "FOOD_DRINK"
    "meal_delivery" => "FOOD_DRINK"
    "meal_takeaway" => "FOOD_DRINK"
    "mediterranean_restaurant" => "FOOD_DRINK"
    "mexican_restaurant" => "FOOD_DRINK"
    "middle_eastern_restaurant" => "FOOD_DRINK"
    "pizza_restaurant" => "FOOD_DRINK"
    "pub" => "FOOD_DRINK"
    "ramen_restaurant" => "FOOD_DRINK"
    "restaurant" => "FOOD_DRINK"
    "sandwich_shop" => "FOOD_DRINK"
    "seafood_restaurant" => "FOOD_DRINK"
    "spanish_restaurant" => "FOOD_DRINK"
    "steak_house" => "FOOD_DRINK"
    "sushi_restaurant" => "FOOD_DRINK"
    "tea_house" => "FOOD_DRINK"
    "thai_restaurant" => "FOOD_DRINK"
    "turkish_restaurant" => "FOOD_DRINK"
    "vegan_restaurant" => "FOOD_DRINK"
    "vegetarian_restaurant" => "FOOD_DRINK"
    "vietnamese_restaurant" => "FOOD_DRINK"
    "wine_bar" => "FOOD_DRINK"
    # Government
    "city_hall" => "GOVERNMENT"
    "courthouse" => "GOVERNMENT"
    "embassy" => "GOVERNMENT"
    "fire_station" => "GOVERNMENT"
    "government_office" => "GOVERNMENT"
    "local_government_office" => "GOVERNMENT"
    "neighborhood_police_station" => "GOVERNMENT"
    "police" => "GOVERNMENT"
    "post_office" => "GOVERNMENT"
    # Health and Wellness
    "chiropractor" => "HEALTH_WELLNESS"
    "dental_clinic" => "HEALTH_WELLNESS"
    "dentist" => "HEALTH_WELLNESS"
    "doctor" => "HEALTH_WELLNESS"
    "drugstore" => "HEALTH_WELLNESS"
    "hospital" => "HEALTH_WELLNESS"
    "massage" => "HEALTH_WELLNESS"
    "medical_lab" => "HEALTH_WELLNESS"
    "pharmacy" => "HEALTH_WELLNESS"
    "physiotherapist" => "HEALTH_WELLNESS"
    "sauna" => "HEALTH_WELLNESS"
    "skin_care_clinic" => "HEALTH_WELLNESS"
    "spa" => "HEALTH_WELLNESS"
    "tanning_studio" => "HEALTH_WELLNESS"
    "wellness_center" => "HEALTH_WELLNESS"
    "yoga_studio" => "HEALTH_WELLNESS"
    # Lodging
    "bed_and_breakfast" => "LODGING"
    "budget_japanese_inn" => "LODGING"
    "campground" => "LODGING"
    "camping_cabin" => "LODGING"
    "cottage" => "LODGING"
    "extended_stay_hotel" => "LODGING"
    "farmstay" => "LODGING"
    "guest_house" => "LODGING"
    "hostel" => "LODGING"
    "hotel" => "LODGING"
    "inn" => "LODGING"
    "japanese_inn" => "LODGING"
    "lodging" => "LODGING"
    "mobile_home_park" => "LODGING"
    "motel" => "LODGING"
    "private_guest_room" => "LODGING"
    "resort_hotel" => "LODGING"
    "rv_park" => "LODGING"
    # Natural Features
    "beach" => "NATURAL_FEATURE"
    # Places of Worship
    "church" => "PLACE_OF_WORSHIP"
    "hindu_temple" => "PLACE_OF_WORSHIP"
    "mosque" => "PLACE_OF_WORSHIP"
    "synagogue" => "PLACE_OF_WORSHIP"
    # Services
    "astrologer" => "SERVICES"
    "barber_shop" => "SERVICES"
    "beautician" => "SERVICES"
    "beauty_salon" => "SERVICES"
    "body_art_service" => "SERVICES"
    "catering_service" => "SERVICES"
    "cemetery" => "SERVICES"
    "child_care_agency" => "SERVICES"
    "consultant" => "SERVICES"
    "courier_service" => "SERVICES"
    "electrician" => "SERVICES"
    "florist" => "SERVICES"
    "food_delivery" => "SERVICES"
    "foot_care" => "SERVICES"
    "funeral_home" => "SERVICES"
    "hair_care" => "SERVICES"
    "hair_salon" => "SERVICES"
    "insurance_agency" => "SERVICES"
    "laundry" => "SERVICES"
    "lawyer" => "SERVICES"
    "locksmith" => "SERVICES"
    "makeup_artist" => "SERVICES"
    "moving_company" => "SERVICES"
    "nail_salon" => "SERVICES"
    "painter" => "SERVICES"
    "plumber" => "SERVICES"
    "psychic" => "SERVICES"
    "real_estate_agency" => "SERVICES"
    "roofing_contractor" => "SERVICES"
    "storage" => "SERVICES"
    "summer_camp_organizer" => "SERVICES"
    "tailor" => "SERVICES"
    "telecommunications_service_provider" => "SERVICES"
    "tour_agency" => "SERVICES"
    "tourist_information_center" => "SERVICES"
    "travel_agency" => "SERVICES"
    "veterinary_care" => "SERVICES"
    # Shopping
    "asian_grocery_store" => "SHOPPING"
    "auto_parts_store" => "SHOPPING"
    "bicycle_store" => "SHOPPING"
    "book_store" => "SHOPPING"
    "butcher_shop" => "SHOPPING"
    "cell_phone_store" => "SHOPPING"
    "clothing_store" => "SHOPPING"
    "convenience_store" => "SHOPPING"
    "department_store" => "SHOPPING"
    "discount_store" => "SHOPPING"
    "electronics_store" => "SHOPPING"
    "food_store" => "SHOPPING"
    "furniture_store" => "SHOPPING"
    "gift_shop" => "SHOPPING"
    "grocery_store" => "SHOPPING"
    "hardware_store" => "SHOPPING"
    "home_goods_store" => "SHOPPING"
    "home_improvement_store" => "SHOPPING"
    "jewelry_store" => "SHOPPING"
    "liquor_store" => "SHOPPING"
    "market" => "SHOPPING"
    "pet_store" => "SHOPPING"
    "shoe_store" => "SHOPPING"
    "shopping_mall" => "SHOPPING"
    "sporting_goods_store" => "SHOPPING"
    "store" => "SHOPPING"
    "supermarket" => "SHOPPING"
    "warehouse_store" => "SHOPPING"
    "wholesaler" => "SHOPPING"
    # Sports
    "arena" => "SPORTS"
    "athletic_field" => "SPORTS"
    "fishing_charter" => "SPORTS"
    "fishing_pond" => "SPORTS"
    "fitness_center" => "SPORTS"
    "golf_course" => "SPORTS"
    "gym" => "SPORTS"
    "ice_skating_rink" => "SPORTS"
    "playground" => "SPORTS"
    "ski_resort" => "SPORTS"
    "sports_activity_location" => "SPORTS"
    "sports_club" => "SPORTS"
    "sports_coaching" => "SPORTS"
    "sports_complex" => "SPORTS"
    "stadium" => "SPORTS"
    "swimming_pool" => "SPORTS"
    # Transportation
    "airport" => "TRANSPORTATION"
    "airstrip" => "TRANSPORTATION"
    "bus_station" => "TRANSPORTATION"
    "bus_stop" => "TRANSPORTATION"
    "ferry_terminal" => "TRANSPORTATION"
    "heliport" => "TRANSPORTATION"
    "international_airport" => "TRANSPORTATION"
    "light_rail_station" => "TRANSPORTATION"
    "park_and_ride" => "TRANSPORTATION"
    "subway_station" => "TRANSPORTATION"
    "taxi_stand" => "TRANSPORTATION"
    "train_station" => "TRANSPORTATION"
    "transit_depot" => "TRANSPORTATION"
    "transit_station" => "TRANSPORTATION"
    "truck_stop" => "TRANSPORTATION"

    _ => "" # Default case
end
